title: Train of Thought
#email: info@westermo.com
description: >-
  Ramblings of software engineers building networking hardware using Linux.
baseurl: ""
url: "https://westermo.github.io"
#twitter_username: westermo
github_username:  westermo

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
